aiosmtpd==1.3.1; python_version<="3.9"
aiosmtpd==1.4.0; python_version>="3.10"
cryptography==3.4.4
pytest==6.0.0; python_version<="3.9"
pytest==6.2.5; python_version>="3.10"  # Due to an error with assertion rewrites under 3.10
python-dotenv==0.8.0
# Test fixtures
pytest-asyncio==0.11.0
pytest-timeout==1.0.0
